import operator
from typing import Annotated, Sequence, TypedDict

from langchain_core.messages import BaseMessage


class AgentState(TypedDict):
    """
    The state of our multi-agent workflow.
    """
    # The main objective of the workflow
    objective: str
    
    # The history of messages passed between agents
    messages: Annotated[Sequence[BaseMessage], operator.add]
    
    # The id of the agent who last spoke
    sender: str
    
    # A specific plan generated by the Planner, if any
    plan: str
